apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
      kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: memealyzernetwebapp
          servicePort: 1080
      - path: /images
        backend:
          serviceName: memealyzernetapi
          servicePort: 2080
      - path: /image
        backend:
          serviceName: memealyzernetapi
          servicePort: 2080
      - path: /config
        backend:
          serviceName: memealyzernetapi
          servicePort: 2080
      - path: /imagehub
        backend:
          serviceName: memealyzernetapi
          servicePort: 2080