kind: ConfigMap
metadata:
  name: websettings
apiVersion: v1
data:
  appsettings.json: |-
    {
        "API_ENDPOINT": "http://localhost:31389",
        "FUNCTIONS_ENDPOINT": "${FUNCTIONS_ENDPOINT}"
    }
